### ISSUE TITLE
공지사항 컴포넌트 수정 요청

### ISSUE THREAD

**Issue by suhongkim98** [1sTeam/all-knu-mobile#23]
![image](https://user-images.githubusercontent.com/35598710/163545745-74d0e400-5ac4-48cd-8d6b-029517ce65cd.png)

제목이 길 경우 ...으로 짤려서 보입니다.
긴 경우 한 줄 내려서 전체적으로 다 보이도록 수정해주세요!

**Comment by sanghyuk-2i** [comment]
[디자인 개선]

CommonItem 컴포넌트에 대한 디자인 개선
- 정기 회의 및 Issue 언급으로 인한 디자인 문제(제목이 한 눈에 안 보이는 현상)
- 회의 때 제시한 아이디어로 디자인 개선(아이콘 크기 및 폰트 사이즈 수정)
- 학교 공지 및 알림 페이지 동시에 적용 대상

#39 

(만족하면 PR 부탁드립니다~)

[디자인 결과]
![IMG_5177](https://user-images.githubusercontent.com/26353827/163802955-5992d475-1641-484f-af06-44ea3fc07d0c.PNG)

**Comment by sanghyuk-2i** [comment]
추가적으로 현재 폰트 크기를 작게 하거나, 두 줄로 했을 경우의 가독성이 불편할 것으로 생각하며 
현재로써는 이 디자인이 최선일 수도...그럴 가능성이 있으며 특히 학교측에서도 이미 "제목명 가독성"에 대해서 이미 문제인거 알고 있는 상황입니다
