### ISSUE TITLE
만족도 조사 참여여부 수정 요청

### ISSUE THREAD

**Issue by suhongkim98** [1sTeam/all-knu-mobile#26]
# 애플리케이션 화면
![image](https://user-images.githubusercontent.com/35598710/163559106-972e1983-7444-4470-924d-9e8e8fcc4eb4.png)

# 참인재시스템
<img width="1049" alt="image" src="https://user-images.githubusercontent.com/35598710/163559192-c8819584-0533-4098-bd38-8411a6da5c1c.png">

# postman
<img width="453" alt="image" src="https://user-images.githubusercontent.com/35598710/163559154-64d2140f-1d8a-4542-8981-bee9a7f21991.png">

# 수정요청
비교과프로그램 중 만족도 설문조사가 없는 프로그램(종료일이 없음)이 있는 것 같습니다.
미응답이지만 링크가 null인 경우 현재는 만족도조사를 해달라고 보여지지만 "참여기간종료"으로 보이게 해주세요

백엔드 쪽에서는 endDate 필드를 null로 수정하겠습니다

**Comment by sanghyuk-2i** [comment]
#35
