### ISSUE TITLE
자동 로그인 시 사진이 불러오지 않는 문제 해결 요청

### ISSUE THREAD

**Issue by suhongkim98** [1sTeam/all-knu-mobile#27]
## 이미지
![image](https://user-images.githubusercontent.com/35598710/163561280-3c93a85f-242d-40da-8617-1a8981d2916e.png)

## 수정요청

직접 로그인 시에는 사진이 정상적으로 보이지만
**로그인을 한 후 -> 앱을 완전 종료(슬라이드해서 앱을 완전히 끔) -> 다시 앱을 켜서 자동로그인 시** 사진이 불러오지 않아지는 문제 확인하였습니다.

**Comment by sanghyuk-2i** [comment]
[버그 수정]

자동 로그인 시, 프로필 사진 로딩이 안되는 문제
- Base64 이미지에 대한 width, height 값을 정적으로 변환(주 원인)
- StudentCard에 대한 Re-Render 구조 개선
- 첫 로그인 시만 네트워크를 통해서 이미지를 불러와 Device에 저장하며 로그아웃 이전까지에 대한 프로필 사진 호출이 있을 경우 Local로 통해서 불러오는 방식이라 기존보다 로딩 속도 개선

#37
