### ISSUE TITLE
WebView 컴포넌트 뒤로가기 화살표 요청

### ISSUE THREAD

**Issue by suhongkim98** [1sTeam/all-knu-mobile#28]
![image](https://user-images.githubusercontent.com/35598710/163562042-ad82139d-39b3-42fb-badf-a22e13d64f09.png)

## 수정 요청

왼쪽으로 슬라이드 해도 웹뷰가 닫히지만 위 상단 **Web 왼쪽 영역**을 클릭해도 웹뷰가 닫히는 것을 확인하였습니다.

이 부분에 뒤로가기 모양 아이콘을 넣어 시각적으로 보여지게 해주세요!

**Comment by sanghyuk-2i** [comment]
[버그 수정]

iOS WebView로 넘어갔을 때, Header에 있는 "뒤로가기" 버튼이 나타나지 않는 현상 해결!
만족도 조사 종료일 null값에 대한 처리

#35
