### ISSUE TITLE
비교과리스트 조회 페이지 수정

### ISSUE THREAD

**Issue by suhongkim98** [1sTeam/all-knu-mobile#29]
**To Reproduce**
어떤 과정을 거쳐 버그가 발생했는지 자세하게 작성해 주세요.
![image](https://user-images.githubusercontent.com/35598710/163583681-99a50156-102d-43f9-a294-0e2373598ca5.png)

비교과리스트 조회가 되지 않습니다!

**Comment by sanghyuk-2i** [comment]
#41 

1차적으로 바교과 전체 리스트를 조회할 수 있는 검색 기능을 만들었습니다.
검색 방식은 간단하게 입력한 단어가 각 Item의 제목명에 포함이 될 경우 리스트를 필터화해서 재출력합니다.
단, 검색 입력란이 아무것도 없으면 그냥 전체 리스트가 출력됩니다.
