### ISSUE TITLE
학사일정 오류

### ISSUE THREAD

**Issue by skfkgla** [1sTeam/all-knu-mobile#34]
**To Reproduce**
로그인 후 첫 화면에서 학사일정을 넘겼을 경우(월별 말고 옆으로 슬라이드) 될 때가 있고 안될 때가 있음

**Error reponse**
응답 에러 내용을 복사 붙여넣기 해주세요.
<img src="https://user-images.githubusercontent.com/79778428/163741329-34bfa31f-a853-4805-9ff2-8800e4ca46fd.jpg">

**Additional context**
옆으로 넘기면 원래 값이 보여야하는데 없음

**Comment by sanghyuk-2i** [comment]
[버그 수정]

학사 일정 가로 스크롤에 대한 버그 수정
- 가로 스크롤 버그 및 가로에 대한 인터페이스 불편을 해소하기 위해 아에 세로 스크롤로 전환
- SubList에 대한 초기 값 미설정에 대한 수정(최초 태그 라인이 안 뜨는 현상 해결)

#42
