### ISSUE TITLE
성적조회 레이아웃 변경 요청

### ISSUE THREAD

**Issue by suhongkim98** [1sTeam/all-knu-mobile#36]
**Describe**
추가하고자 하는 기능에 대해 최대한 자세하게 설명해주세요.

![image](https://user-images.githubusercontent.com/35598710/163757008-e5cc3ebf-aa3c-403f-9093-096c9d0166bb.png)

현재는 아이템이 2개가 최대고 옆으로 슬라이드하며 성적을 조회합니다.
한 학기에 성적 아이템은 많아봐야 8개를 넘기 힘드니 슬라이드 방식이 아니라 그냥 한눈에 보여지도록 하는 것이 더 좋을 것 같습니다. 가능할까요?

**Comment by sanghyuk-2i** [comment]
[개선 사항]

종합정보시스템의 성적 조회 페이지 대한 취득 정보 구조 개선

가로 슬라이드 형식으로 봐야 했던 성적을 스크롤 방식으로 변경하여 한 눈에 보기 쉽게 변경
학기 변경해도 문제없이 잘 작동되는 것을 확인!

#38
